### ISSUE TITLE
Fatal error occurs!

### ISSUE THREAD

**Issue by Light--** [Testzero-wz/wscan#1]
$ wscan -u "https://xxx/" -f -m

        ___      ____________________ _______ 
        __ | /| / /_  ___/  ___/  __ `/_  __ \
        __ |/ |/ /_(__  )/ /__ / /_/ /_  / / /
        ____/|__/ /____/ \___/ \__,_/ /_/ /_/ 
        
          Blog: <https://www.testzero-wz.com>
          Email: <testzero.wz@gmail.com>

[*] Start: 18:04:27
[*] Start Mapping...
[-] Fatal error occurs!
[-] Error: 
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f98ea9ea710>
/home/user/.local/lib/python3.6/site-packages/wscan/lib/controller/Controller.py:475: RuntimeWarning: coroutine 'noop2' was never awaited
  self.session._connector.close()
Task was destroyed but it is pending!
task: <Task pending coro=<TCPConnector._resolve_host() running at /home/user/.local/lib/python3.6/site-packages/aiohttp/connector.py:830> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7f98e5a248b8>()]> cb=[shield.<locals>._done_callback() at /usr/lib/python3.6/asyncio/tasks.py:688]>

**Comment by Testzero-wz** [comment]
Hi，我在本地测试中并未出现类似的错误，我把本地的最新版**2.4.3**更新到了github和pypi上
你可以用命令
`python3 -m pip install wscan==2.4.3`
进行更新，并重新运行wscan。
我已取消错误显示优化，程序运行出现错误将显示详细信息。
若问题依旧出现，烦请给出详细的错误信息，运行参数，python版本，操作系统等关键信息以帮助我debug：）

**Comment by Light--** [comment]
> 若问题依旧出现，烦请给出详细的错误信息，运行参数，python版本，操作系统等关键信息以帮助我debug：）

安装了新的版本但这次出现的错误好像和上次不一样：好像是联网问题
python3.6.9 ubuntu16.04 运行参数和详细错误信息如下。
我就是想看一下这个URL后台有哪些目录可以找到。比如我现在自己手动找到了 codes demos等文件夹，想看看还有没有别的。暂时不需要下载文件。（加上-m参数输出结果相同）

我是通过代理上网，但是已经export 了 http_proxy和https_proxy，并不管用。。
```
$ wscan -u "https://www.xxx" -f

        ___      ____________________ _______ 
        __ | /| / /_  ___/  ___/  __ `/_  __ \
        __ |/ |/ /_(__  )/ /__ / /_/ /_  / / /
        ____/|__/ /____/ \___/ \__,_/ /_/ /_/ 
        
          Blog: <https://www.testzero-wz.com>
          Email: <testzero.wz@gmail.com>


[*] Start: 12:32:13
[-] Fatal error occurs!
Traceback (most recent call last):
  File "/home/user/.local/bin/wscan", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/wscan/main.py", line 24, in main
    wscan()
  File "/home/user/.local/lib/python3.6/site-packages/wscan/main.py", line 20, in __init__
    self.control.start()
  File "/home/user/.local/lib/python3.6/site-packages/wscan/lib/controller/Controller.py", line 434, in start
    raise e
  File "/home/user/.local/lib/python3.6/site-packages/wscan/lib/controller/Controller.py", line 426, in start
    self.__start()
  File "/home/user/.local/lib/python3.6/site-packages/wscan/lib/controller/Controller.py", line 407, in __start
    self.__init__404_page()
  File "/home/user/.local/lib/python3.6/site-packages/wscan/lib/controller/Controller.py", line 106, in __init__404_page
    self.loop.run_until_complete(self.process_404(_404_url))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.6/site-packages/wscan/lib/controller/Controller.py", line 109, in process_404
    _404_res = await self.get_response(url, allow_redirects=True)
  File "/home/user/.local/lib/python3.6/site-packages/wscan/lib/controller/Controller.py", line 280, in get_response
    return await self.session.get(url, timeout=timeout, allow_redirects=allow_redirects, headers=headers)
  File "/home/user/.local/lib/python3.6/site-packages/aiohttp/client.py", line 582, in _request
    break
  File "/home/user/.local/lib/python3.6/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3c8ae6efd0>
Task exception was never retrieved
future: <Task finished coro=<TCPConnector._resolve_host() done, defined at /home/user/.local/lib/python3.6/site-packages/aiohttp/connector.py:774> exception=gaierror(-3, 'Temporary failure in name resolution')>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/user/.local/lib/python3.6/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by Testzero-wz** [comment]
这是你扫描网站与你的连接超时问题，并非Bug。
经测试，境内连接你的目标网站延迟10s左右（默认超时时间12s），导致自动检测404页面的出现超时终止，程序退出。
目前已优化404页面超时，参数跟随全体页面超时时间，也就是依靠参数`-t <NUM>`指定。
你可以更新到**2.4.31**版本
`python3 -m pip install wscan==2.4.31`
然后按照你实际代理的速度进行调整扫描超时时间（参数`-t <NUM>`），并且根据网站承受程度指定扫描协程数（参数`-max <NUM>`）。
（个人建议：你的目标网站响应较慢，超长时间扫描是免不了的，而且目标网站比较“脆弱”，推荐减少协程数5-10）
`wscan -u "https://www.cs.tau.ac.il/~wolf/" -f -t 60 -v -max 8`

**Comment by Light--** [comment]
按照你说的改了，没有任何有意义的输出，即使我把超时设到了100
所以你的超时设置是不是应该根据页面响应时间自适应一下？
```
$ wscan -u "https://xxx" -f -t 100 -v -max 8

        ___      ____________________ _______ 
        __ | /| / /_  ___/  ___/  __ `/_  __ \
        __ |/ |/ /_(__  )/ /__ / /_/ /_  / / /
        ____/|__/ /____/ \___/ \__,_/ /_/ /_/ 
        
          Blog: <https://www.testzero-wz.com>
          Email: <testzero.wz@gmail.com>


[*] Start: 11:34:30
[-] Something wrong when init 404 page
[-] ERR: Cannot connect to host www.xxx:443 ssl:default [Temporary failure in name resolution]
[!] Auto detect 404 func will be close. But you can still scan.
[*] Start Fuzzing...
[*] End: 15:46:48

==========================================================================================
Web site map:
 +-- / 404

==========================================================================================
[*] Scan finished. Cost 15137.40 s.

```

**Comment by Testzero-wz** [comment]
错误提示已经说明问题了，无法解析域名。
依旧为网络原因，建议更换代理或不使用代理，issue关闭。
（即使是python库源码也是有默认的请求超时时间，当有一个请求被阻塞时，应该思考为什么会阻塞到超时的问题而不应该思考为何超时时间自适应的问题。
即便这样，你将超时时间设置为无限大如999999就能达到所期望的“自适应”效果。）
不使用代理扫描效果如下：
```
wscan -u "https://www.cs.tau.ac.il/~wolf/" -f -t 100 -v -max 8

        ___      ____________________ _______ 
        __ | /| / /_  ___/  ___/  __ `/_  __ \
        __ |/ |/ /_(__  )/ /__ / /_/ /_  / / /
        ____/|__/ /____/ \___/ \__,_/ /_/ /_/ 
        
          Blog: <https://www.testzero-wz.com>
          Email: <testzero.wz@gmail.com>


[*] Start: 22:31:32
[*] Start Fuzzing...
[*] 403 - AT-admin.cgi
[*] 403 - auth.cgi
[*] 403 - auth.pl
[*] 403 - awstats.pl
[*] 403 - cachemgr.cgi
[*] 403 - cgi-bin/awstats.pl
[*] 301 - cgi-bin => 200 - https://www.cs.tau.ac.il/~wolf/cgi-bin/
[*] 200 - cgi-bin/
[*] 403 - cgi-bin/test.cgi
[*] 403 - cgi.pl/
[*] 403 - Cgishell.pl
[*] 301 - code => 200 - https://www.cs.tau.ac.il/~wolf/code/
[*] 301 - data => 200 - https://www.cs.tau.ac.il/~wolf/data/
[*] 403 - dcadmin.cgi
[*] 403 - gbpass.pl
[*] 301 - images => 200 - https://www.cs.tau.ac.il/~wolf/images/
[*] 301 - index_files => 200 - https://www.cs.tau.ac.il/~wolf/index_files/
[*] 200 - index.html
[*] 403 - out.cgi
[*] 301 - papers => 200 - https://www.cs.tau.ac.il/~wolf/papers/
[*] 403 - perl-reverse-shell.pl
[*] 403 - perlcmd.cgi
[*] 301 - pics => 200 - https://www.cs.tau.ac.il/~wolf/pics/
[*] 403 - ps_admin.cgi
[*] 200 - robots.txt
[*] 403 - Signin.cgi
[*] 403 - signin.cgi
[*] 301 - survey => 200 - https://www.cs.tau.ac.il/~wolf/survey/
[*] 403 - Symlink.pl
[*] 200 - Thumbs.db
[*] 403 - tmp
[*] 200 - upload.html
[*] 301 - us => 200 - https://www.cs.tau.ac.il/~wolf/us/
[*] 403 - WebShell.cgi
[*] End: 22:43:13

========================================================
Web site map:
 +-- / 404
 │    +-- cgi-bin 200
 │    +-- code 200
 │    +-- data 200
 │    +-- images 200
 │    +-- index_files 200
 │    +-- index.html 200
 │    +-- papers 200
 │    +-- pics 200
 │    +-- robots.txt 200
 │    +-- survey 200
 │    +-- Thumbs.db 200
 │    +-- upload.html 200
 │    +-- us 200

===========================================================
[*] Scan finished. Cost 700.41 s.
```

**Comment by Light--** [comment]
> 错误提示已经说明问题了，无法解析域名。
> 依旧为网络原因，建议更换代理或不使用代理，issue关闭。

谢谢！如果程序能够确定代理联网出现问题，应该终止然后退出？提示进行正确的代理设置什么的。。不应该继续这么耗时的扫描下去吧。小建议
